---
- hosts: all
  tasks:
  - name: Group machines by OS distrobution
    action: group_by key={{ ansible_os_family }}

- hosts: RedHat
  become: true
  tasks:
  - import_role: 
     name: redhat

- hosts: Debian
  become: true
  tasks:
  - import_role: 
     name: debian
