- hosts: all

  tasks:


  - name: Create a group of all hosts by operating system
    action: group_by key={{ ansible_os_family }}

# the following host group does not exist in inventory and was created by the group_by
# module.

 
- hosts: RedHat
#
  tasks:
#
  - name: ping all CentOS hosts
    action: ping

  - name: get list of ackages that have updates
    command: yum list updates
    args:
      warn: False
    register: yum_update_packages
    changed_when: 0

  - name: parse yum output to get list of changed packages
    set_fact:
      rhel_updates: "{{ yum_update_packages.stdout_lines| select('match','\\w+-\\w+.\\w+') | list | splitpart(0, ' ') | list | sort }}"
    changed_when: 0

  - name: show pending updates
    debug:
      var: rhel_updates
    when: rhel_updates.0 is defined


    # - name: show pending redhat updates
    #debug:
    #  msg: "{{ yum_update_packages.stdout_lines| select('match','\\w+-\\w+.\\w+') | list | splitpart(0, ' ') | list}}"
            #msg: rhel_updates
      #'{{ apt_simulate.stdout_lines | select("match", "^Inst ") | list | splitpart(1, " ") | list | sort }}'

- hosts: Debian
  tasks:
  - name: List packages that have updates
    command: apt-get --simulate dist-upgrade
    #shell: apt-get --simulate dist-upgrade
    args:
     warn: false
    register: apt_simulate
    changed_when: 0

  - name: parse apt-get output to get list of changed packages
    set_fact:
      updates: "{{ apt_simulate.stdout_lines | select('match', '^Inst ') | list | splitpart(1, ' ') | list | sort }}"
    changed_when: 0

    # tell user about packages being updated
  - name: show pending updates
    debug:
      var: updates
    when: updates.0 is defined

          #    - name: ping lucid hosts 
          #action: ping
          #gather_fact: False
