- hosts: all

  tasks:

          # - name: Create a group of all hosts by operating system
    #action: group_by key=${ansible_distribution}-${ansible_distribution_version}
    #action: group_by key=${ansible_distribution}-${ansible_distribution_version}

  - name: Create a group of all hosts by operating system
    #action: group_by key=${ansible_distribution}-${ansible_distribution_version}
    action: group_by key={{ ansible_os_family }}
  - debug:
        msg: "{{ ansible_os_family }}"
          # - name: register this a lucid
          #action: shell lsb_release -sc 
          #register: codename


          # - name: Create a group of all hosts by operating system
          #action: group_by key=${codename.stdout}


# the following host group does not exist in inventory and was created by the group_by
# module.

 
- hosts: RedHat
#
  tasks:
#
  - name: ping all CentOS hosts
    gather_facts: no
    action: ping

- hosts: Debian
  tasks:

    - name: ping lucid hosts 
      action: ping
      gather_fact: False
